# domain to use when creating the certificate (could be *)
domain = "localhost"
# duration of the certificate in hour
duration = 1
# display of /films/ (use go template format)

[film]
index = """
# Film
{{ range .Films }}
=> /films/{{.Path}} {{ .Title }}{{ end }}
"""
display = """
# {{ .Title }}
{{ range .Tags }}
=> /films/tag/{{ escape . }} {{ . }}{{ end }}
{{ range .Description }}
{{.}}
{{ end }}
=> {{ .Image }} Image de {{ .Title }}
"""