# domain to use when creating the certificate (could be *)
domain = "localhost"
# duration of the certificate in hour
duration = 1

# display of all contents in /films/ (use go template format)
[film]
index = """
# Film
{{ range .Films }}
=> /films/{{.Path}} {{ .Title }}{{ end }}
"""
display = """
# {{ .Title }}
{{ .Author }}, {{ .Year }}
{{ range .Tags }}
=> /films/tag/{{ escape . }} {{ . }}{{ end }}
{{ range .Description }}
{{.}}
{{ end }}
=> {{ .Image }} Image de {{ .Title }}
"""
tag = """
# {{ .Name }}

Films:
{{ range .Films }}
=> /films/{{ .Path }} {{ .Title }} by {{ .Author }} ({{ .Year }}){{ end }}
"""